### ISSUE TITLE
macOS app icon is not correctly rounded

### ISSUE THREAD

**Issue by JosephTico** [outerbase/studio-desktop#1]
And looks pretty bad

![Vivaldi 05-12-05 at 01 28 PM](https://github.com/user-attachments/assets/a5a97c6f-b41f-4ca4-8438-6dc20b0d1a18)

**Comment by invisal** [comment]
<img width="354" alt="Screenshot 2024-12-09 at 8 56 24 in the evening" src="https://github.com/user-attachments/assets/4b151081-4598-49e0-97c3-acbadf5bd54d">

Fixed. Sorry for taking a while to response to your issue. I mostly check other repo and didn't realize people posting issue in the desktop repo :)
