### ISSUE TITLE
Toggle Dark Mode

### ISSUE THREAD

**Issue by roth-dev** [outerbase/studio-desktop#10]

**Comment by garlibe** [comment]
Was about to mention this one. It does have dark mode, but it's not sticky, so every time I reopen Outerbase it's back on light mode.

**Comment by roth-dev** [comment]
I just working on this issue and i believe it will sticky when it's available next version.

**Comment by roth-dev** [comment]
Done https://github.com/outerbase/studio-desktop/pull/11
