### ISSUE TITLE
Json column not showing up properly

### ISSUE THREAD

**Issue by RanaMoizHaider** [outerbase/studio-desktop#2]
I loaded MySQL database in mac version of studio and this is how json column is showing up
<img width="917" alt="image" src="https://github.com/user-attachments/assets/20ee2646-96fa-45c1-80e1-2850a95ec06f">

while expected output should be like this
<img width="795" alt="image" src="https://github.com/user-attachments/assets/77644e82-f65b-47ae-9ef5-cfa9082350ed">

**Comment by invisal** [comment]
Thanks for reporting. I am working on the fix as soon as possible.

**Comment by invisal** [comment]
This should fix in latest versio  v0.1.13.

Sorry for taking too long for reply. I mostly check the main repo and didn't know people report issue in this repo instead.

**Comment by RanaMoizHaider** [comment]
Thank you for the fix.

I too thought of reporting in the main repo first but as there was a dedicated repo for desktop version it was better to report here.
